# Generated by Django 4.2.5 on 2023-09-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(blank=True, max_length=100, null=True)),
                ('two', models.CharField(blank=True, max_length=100, null=True)),
                ('three', models.CharField(blank=True, max_length=100, null=True)),
                ('updatedValue', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='link',
            name='body',
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
